# -*- coding: utf-8 -*-
"""Read the stack-NUMBER printed on an inventory slot (font-independent OCR).

The item recognizer (:mod:`inventory.scanner`) deliberately ZEROES the number
band so an item is identified regardless of its stack count. This module reads
that very band back: the white digit core is thresholded, the digit row-height
is normalised, and the count is decoded by a FIXED-WIDTH try-all-n template
match (n = 1..4 equal cells) so touching digits (the small in-game font) need no
fragile gap segmentation. Each cell is matched (normalised cross-correlation)
against bundled glyph templates -- REAL glyphs extracted from real screenshots
plus SYNTHETIC monospace renders -- and the best digit wins.

Design goals (mirroring the rest of the engine):

  * **Zero user input** -- templates ship in ``inventory_digits/`` (generated by
    ``tools/gen_digit_templates.py``); the user never supplies a digit.
  * **Honest confidence** -- :func:`read_count` returns a confidence and a
    ``confident`` flag; a weak/ambiguous read is reported, never silently
    guessed (the scanner surfaces it as a "scan uncertain" warning).
  * **Never raises** -- soft numpy/PIL imports; degrades to ``None`` + logs.

``read_count(slot_rgb)`` takes ONE ``(SLOT_PX, SLOT_PX, 3)`` float RGB slot
(exactly what :func:`inventory.grid.extract_slot` yields) and returns a
:class:`CountResult`.
"""

import os
from dataclasses import dataclass
from typing import Optional

from respath import resource_path
from i18n import t
from .constants import SLOT_PX

try:  # pragma: no cover
    from debuglog import log
except Exception:  # pragma: no cover
    log = None

try:  # pragma: no cover
    import numpy as np
except Exception:  # pragma: no cover
    np = None

try:  # pragma: no cover
    from PIL import Image as _Image
except Exception:  # pragma: no cover
    _Image = None


DIGIT_DIR = 'inventory_digits'

CANON_H = 16          # canonical glyph height for matching
WHITE_MIN = 150       # min(R,G,B) above which a pixel is "white digit core"
BAND_TOP = 13         # number band = slot rows BAND_TOP..SLOT_PX-1
INK_THR = 0.25        # whiteness above which a pixel counts as ink
MIN_CELL_W = 2        # a digit cell narrower than this (canonical px) is junk
MAX_DIGITS = 4        # stack counts are <= 4 digits in practice
CONF_MIN = 0.46       # weakest-cell NCC to call a read 'confident'
MARGIN_MIN = 0.02     # weakest-cell margin (best - 2nd best digit) to be sure

_TEMPLATES = None     # {int digit: [np.float32 mask (CANON_H, w), ...]}


def _log(key, **fmt):
    if log is None:
        return
    try:
        log.event(0, t(key, **fmt))
    except Exception:
        pass


@dataclass(frozen=True)
class CountResult:
    """Outcome of reading one slot's stack number (immutable).

    :ivar value: decoded integer count; ``1`` when the slot shows no number
        (a single, unstacked item); ``None`` only when reading is impossible
        (no numpy/PIL or no templates).
    :ivar confidence: weakest per-digit match score in ``0..1`` (``1.0`` for the
        no-number case).
    :ivar confident: ``True`` iff every digit cleared CONF_MIN/MARGIN_MIN.
    :ivar n_digits: how many digits were decoded (``0`` for the no-number case).
    """

    value: Optional[int]
    confidence: float
    confident: bool
    n_digits: int


def _digit_dir():
    """Resolve the bundled digit-template dir, cwd-independently (cf. assets)."""
    base = resource_path(DIGIT_DIR)
    if os.path.isdir(base):
        return base
    here = os.path.dirname(os.path.abspath(__file__))
    fallback = os.path.join(os.path.dirname(here), DIGIT_DIR)
    return fallback if os.path.isdir(fallback) else base


def _load_templates():
    """Load + cache ``{digit: [mask, ...]}`` from ``inventory_digits/*.png``.

    Each PNG is named ``<digit>__<tag>.png``; the leading char is the digit. A
    template is a grayscale glyph mask in ``0..1`` (canonical height). Returns
    ``{}`` (logged once) when the dir/PIL/numpy is unavailable -- the reader then
    yields ``None`` counts and the scan is flagged uncertain rather than crash.
    """
    global _TEMPLATES
    if _TEMPLATES is not None:
        return _TEMPLATES
    out = {}
    if _Image is None or np is None:
        _TEMPLATES = out
        return out
    base = _digit_dir()
    try:
        names = sorted(os.listdir(base))
    except Exception as exc:
        _log('inventory.digits_dir_missing', path=base, detail=str(exc)[:120])
        _TEMPLATES = out
        return out
    for name in names:
        if not name.lower().endswith('.png') or '__' not in name:
            continue
        ch = name[0]
        if not ch.isdigit():
            continue
        try:
            with _Image.open(os.path.join(base, name)) as img:
                arr = np.asarray(img.convert('L'), dtype=np.float32) / 255.0
        except Exception:
            continue
        out.setdefault(int(ch), []).append(arr)
    if not out:
        _log('inventory.digits_dir_empty', path=base)
    _TEMPLATES = out
    return out


def _white_mask(band_rgb):
    """Whiteness ``0..1`` of a band: high only where all RGB channels are high."""
    arr = np.asarray(band_rgb, dtype=np.float32)
    mn = arr.min(axis=2)
    return np.clip((mn - WHITE_MIN) / (255.0 - WHITE_MIN), 0.0, 1.0)


def _ink_bbox(mask):
    ys, xs = np.where(mask > INK_THR)
    if len(xs) == 0:
        return None
    return int(xs.min()), int(xs.max()) + 1, int(ys.min()), int(ys.max()) + 1


def _norm_cell(mask):
    """Crop to ink + scale to ``CANON_H`` height (aspect kept). ``None`` if empty."""
    bb = _ink_bbox(mask)
    if bb is None:
        return None
    x0, x1, y0, y1 = bb
    crop = mask[y0:y1, x0:x1]
    new_w = max(MIN_CELL_W,
                int(round(crop.shape[1] * CANON_H / max(1, crop.shape[0]))))
    im = _Image.fromarray((crop * 255).astype('uint8')).resize(
        (new_w, CANON_H), _Image.BILINEAR)
    return np.asarray(im, dtype=np.float32) / 255.0


def _ncc(a, b):
    """Normalised cross-correlation of two masks (b resized to a)."""
    if b.shape != a.shape:
        b = np.asarray(_Image.fromarray((b * 255).astype('uint8')).resize(
            (a.shape[1], a.shape[0]), _Image.BILINEAR), dtype=np.float32) / 255.0
    a = a - a.mean(); b = b - b.mean()
    da = float(np.sqrt((a * a).sum())); db = float(np.sqrt((b * b).sum()))
    if da < 1e-6 or db < 1e-6:
        return 0.0
    return float((a * b).sum() / (da * db))


def _match_cell(cellmask, templates):
    """Best ``(digit, score, margin)`` for one normalised cell, or ``None``."""
    cn = _norm_cell(cellmask)
    if cn is None:
        return None
    scored = []
    for d, tmpls in templates.items():
        scored.append((max(_ncc(cn, tm) for tm in tmpls), d))
    scored.sort(reverse=True)
    top_s, top_d = scored[0]
    margin = top_s - (scored[1][0] if len(scored) > 1 else 0.0)
    return top_d, top_s, margin


def _decode(mask, templates):
    """Fixed-width try-all-n decode -> ``(text, weak_score, weak_margin)``.

    For n = 1..MAX_DIGITS the ink span is split into n equal cells, each cell
    classified; the n whose (mean+min) cell score is highest wins. Returns
    ``('', 0, 0)`` when nothing decodes.
    """
    bb = _ink_bbox(mask)
    if bb is None:
        return '', 0.0, 0.0
    x0, x1 = bb[0], bb[1]
    width = x1 - x0
    best = None
    for n in range(1, MAX_DIGITS + 1):
        cw = width / n
        if cw < MIN_CELL_W:
            break
        digits, scores, margins = [], [], []
        ok = True
        for i in range(n):
            cs = int(round(x0 + i * cw)); ce = int(round(x0 + (i + 1) * cw))
            m = _match_cell(mask[:, cs:ce], templates)
            if m is None:
                ok = False
                break
            digits.append(str(m[0])); scores.append(m[1]); margins.append(m[2])
        if not ok:
            continue
        mean_s = sum(scores) / len(scores)
        min_s = min(scores)
        key = mean_s + min_s
        if best is None or key > best[0]:
            best = (key, ''.join(digits), min_s, min(margins))
    if best is None:
        return '', 0.0, 0.0
    return best[1], best[2], best[3]


def read_count(slot_rgb):
    """Read the stack number on one slot. Returns a :class:`CountResult`.

    ``slot_rgb`` is a ``(SLOT_PX, SLOT_PX, 3)`` float/uint RGB array (as
    :func:`inventory.grid.extract_slot` yields). A slot with no white digit ink
    is a single, unstacked item -> ``value=1, n_digits=0``. Never raises.
    """
    if np is None or _Image is None or slot_rgb is None:
        return CountResult(None, 0.0, False, 0)
    arr = np.asarray(slot_rgb, dtype=np.float32)
    if arr.ndim != 3 or arr.shape[2] < 3 or arr.shape[0] < SLOT_PX:
        return CountResult(None, 0.0, False, 0)
    templates = _load_templates()
    if not templates:
        return CountResult(None, 0.0, False, 0)
    band = arr[BAND_TOP:SLOT_PX, :, :3]
    mask = _white_mask(band)
    if _ink_bbox(mask) is None:
        return CountResult(1, 1.0, True, 0)        # no number -> single item
    text, weak_score, weak_margin = _decode(mask, templates)
    if not text.isdigit():
        return CountResult(None, float(weak_score), False, 0)
    confident = (weak_score >= CONF_MIN and weak_margin >= MARGIN_MIN)
    return CountResult(int(text), float(weak_score), confident, len(text))
